### ISSUE TITLE
Path to files

### ISSUE THREAD

**Issue by davidmaillo** [kylejkent/google-search-backend#1]
You don't want to path your files with "./"

https://github.com/kylejkent/google-search-backend/blob/e4443e0bf3ec43fa88d7dce0acbac57f5db26b97/views/results.hbs#L4

**Comment by kylejkent** [comment]
Believe fixed with https://github.com/kylejkent/google-search-backend/commit/ad3995099cb8f9c36cf59df6702c29c9f05be632
